const lyricsData = [
  { title: "Shape of You", lyrics: "I'm in love with the shape of you, we push and pull like a magnet do..." },
  { title: "Blinding Lights", lyrics: "I said, ooh, I'm blinded by the lights, no, I can't sleep until I feel your touch..." },
  { title: "Someone Like You", lyrics: "Nevermind, I'll find someone like you, I wish nothing but the best for you too..." },
  { title: "Bohemian Rhapsody", lyrics: "Is this the real life? Is this just fantasy? Caught in a landslide, no escape from reality..." },
  { title: "Rolling in the Deep", lyrics: "We could have had it all, rolling in the deep, you had my heart inside of your hands..." },
  { title: "Love Yourself", lyrics: "Cause if you like the way you look that much, oh baby, you should go and love yourself..." },
  { title: "Hotel California", lyrics: "Welcome to the Hotel California, such a lovely place, such a lovely face..." },
  { title: "Counting Stars", lyrics: "Lately, I've been, I've been losing sleep, dreaming about the things that we could be..." },
  { title: "Billie Jean", lyrics: "Billie Jean is not my lover, she's just a girl who claims that I am the one..." },
  { title: "Sugar", lyrics: "Sugar, yes, please, won't you come and put it down on me?..." },
  { title: "Let It Be", lyrics: "When I find myself in times of trouble, Mother Mary comes to me, speaking words of wisdom, let it be..." },
  { title: "Yesterday", lyrics: "Yesterday, all my troubles seemed so far away, now it looks as though they're here to stay..." },
  { title: "Hey Jude", lyrics: "Hey Jude, don't make it bad, take a sad song and make it better..." },
  { title: "Take Me Home, Country Roads", lyrics: "Country roads, take me home, to the place I belong..." },
  { title: "Shallow", lyrics: "I'm off the deep end, watch as I dive in, I'll never meet the ground..." },
  { title: "Tum Hi Ho", lyrics: "Tum hi ho, ab tum hi ho, zindagi ab tum hi ho..." },
  { title: "Kesariya", lyrics: "Kesariya tera ishq hai piya, rang jaaun jo main haath lagaaun..." },
  { title: "Chaiyya Chaiyya", lyrics: "Jinke sar ho ishq ki chaaon, paaon ke neeche jannat hogi..." },
  { title: "Kal Ho Na Ho", lyrics: "Har ghadi badal rahi hai roop zindagi, chaav hai kabhi, kabhi hai dhoop zindagi..." },
  { title: "Gallan Goodiyan", lyrics: "Gallan goodiyan... gallan goodiyan, aaja dil diyan gallan kar laye..." },
  { title: "Agar Tum Saath Ho", lyrics: "Agar tum saath ho, ro len do, behne do..." },
  { title: "Tera Ban Jaunga", lyrics: "Main tera ban jaunga, ke main tera ban jaunga..." },
  { title: "Raataan Lambiyan", lyrics: "Raataan lambiyan lambiyan re, katein tere sangeyaan sangeyaan re..." },
  { title: "Tum Se Hi", lyrics: "Tum se hi, din hota hai, surmayi shaam aati hai, tum se hi..." },
  { title: "Jai Ho", lyrics: "Jai ho, aaja aaja jind shamiyane ke tale, aaja jariwale nile aasman ke tale..." },
  { title: "Jeene Laga Hoon", lyrics: "Jeene laga hoon, pehle se zyada, pehle se zyada tumpe marne laga hoon..." },
  { title: "Sun Saathiya", lyrics: "Sun saathiya, maahiya, barsa de, ishqa ki syahiyaan..." },
  { title: "Pee Loon", lyrics: "Pee loon, tere neele neele nainon se shabnam, pee loon..." },
  { title: "Hasi", lyrics: "Hasi ban gaye, hasi ban gaye, tum mere aasmaan meri zameen ban gaye..." },
  { title: "Tera Hone Laga Hoon", lyrics: "Shining in the setting sun like a pearl upon the ocean, come and feel me, oh, feel me..." },
];

export default lyricsData;
